version: '3.8'

services:
  ansible:
    profiles:
      - ansible
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - "medyk/ansible:6"
        - "medyk/ansible:latest"
    image: medyk/ansible:latest
    volumes:
      - ./inventory:/inventory
      - ./playbooks:/playbooks
    network_mode: host
    command: ["bash"]

  vault:
    image: vault:1.12.1
    restart: always
    env_file:
      - vault.env
    cap_add:
      - IPC_LOCK
    ports:
      - "8200:8200"
    volumes:
      - ./vault/config:/vault/config
      - ./vault/file:/vault/file
      - ./vault/logs:/vault/logs
    entrypoint: vault server -config=/vault/config/vault.hcl
